#!/bin/bash
#
# binl		This shell script takes care of starting and stopping
#		the binl service
#
# chkconfig: - 58 74
# description: binl service for windows RIS. 

# Source function library.
. /etc/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

devcache=/etc/devlist.cache
logfile=/var/public/log/binl.log

RETVAL=0
prog="binlserver"

start() {
        # Start daemons.
        echo -n $"Starting $prog: "
        /var/public/bin/binlsrv2.py -d -l $logfile $devcache
        RETVAL=$?
	return $RETVAL
}

stop() {
        echo -n $"Shutting down $prog: "
	pkill -f binlsrv2.py
        rm -f /var/run/binlsrv.pid
        RETVAL=$?
	return $RETVAL
}

# See how we were called.
case "$1" in
  start)
	start
	RETVAL=$?
        [ $RETVAL -eq 0 ] && echo_success || echo_failure
        echo
        ;;
  stop)
	stop
	RETVAL=$?
        [ $RETVAL -eq 0 ] && echo_success || echo_failure
        echo
        ;;
  restart|reload)
	stop
        [ $RETVAL -eq 0 ] && echo_success || echo_failure
        echo
	start
	RETVAL=$?
        [ $RETVAL -eq 0 ] && echo_success || echo_failure
        echo
	;;
  *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $RETVAL
